language: node_js
node_js: "node"
cache: npm
install:
  - npm ci
  - npm install -g codecov
script:
  - npm run build
  - npm test
  - codecov
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t yingrui205/sast-app-web .
  - docker push yingrui205/sast-app-web
